project_id = "joihvetbtjyrdcoflcgv"

[functions.daily-scripture]
verify_jwt = false

[functions.auto-like-god]
verify_jwt = false

[functions.fetch-news]
verify_jwt = false

[functions.password-reset]
verify_jwt = false

[functions.livekit-token]
verify_jwt = true
